baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Nexus Web'
theme = 'nexus'

[outputs]
  home = ["HTML", "JSON", "RSS", "Sitemap"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  taxonomy = ["HTML"]

[sitemap]
  changeFreq = 'weekly'
  priority = 0.5

[pagination]
  pagerSize = 5
  path = 'page'

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[author]
  name = "Ibrahim Al Naz Rana"

[params]
  subtitle = "@ranabd36"
  favicon = "/img/favicon.ico"
  description = "Discover how to unleash the full potential of web development among others at Nexus Web. This is where you will find the most comprehensive guides on PHP, Laravel, Go, SQL and JavaScript just to mention a few."
  keywords = "blog, technology, PHP tutorials, Laravel guides, Go programming, SQL tips, JavaScript learning, Linux tutorials, macOS tips, Web development, Programming tutorials, Coding best practices"
  image = "/img/default-og-image.webp"
  twitter_site = "@ranabd36"
  twitter_image = "/img/default-og-image.webp"
  google_analytics = "G-PPGWY8TKX7"
  facebook_app_id = "377744055369086"

  [menu]
   [[menu.main]]
     identifier = "category"
     name = "Categories"
     url = "/categories/"

   [[menu.main]]
     identifier = "series"
     name = "Series"
     url = "/series/"
     
   [[menu.main]]
     identifier = "contact"
     name = "Contact"
     url = "/contact/"
     
  [[menu.social]]
    identifier = "mail"
    name = "Email"
    url = "mailto:ranabd36@gmail.com"
    
  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ranabd36"

  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ranabd36"