baseURL = 'https://ranabd36.github.io/nexusweb-blog/'
languageCode = 'en-us'
title = 'Nexus Web'
theme = 'tophat'
paginate = 5

[params]
  main = "posts"
  featured = false
  description = "@ranabd36"
  favicon = "/img/favicon.png"
  # You can customize the visibility of some elements like date, reading time, words counter and tags inside article by setting true or false
  show_date_on_article = true
  show_reading_time_on_article = true
  show_words_count_on_article = false
  show_tags_on_article = true

  [menu]

#   [[menu.main]]
#     identifier = "about"
#     name = "About"
#     url = "/pages/about/"

#   [[menu.main]]
#     identifier = "contact"
#     name = "Contact"
#     url = "/pages/contact/"

  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ranabd36"

  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ranabd36"