baseURL = 'https://www.nexusweb.net/'
languageCode = 'en-us'
title = 'Nexus Web'
theme = 'nexus'

[outputs]
  home = ["HTML", "JSON"]

[pagination]
  pagerSize = 5
  path = 'page'

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  main = "posts"
  featured = false
  subtitle = "@ranabd36"
  favicon = "/img/favicon.png"
  # You can customize the visibility of some elements like date, reading time, words counter and tags inside article by setting true or false
  show_date_on_article = true
  show_reading_time_on_article = true
  show_words_count_on_article = false
  show_tags_on_article = true

  [menu]
   [[menu.main]]
     identifier = "category"
     name = "Categories"
     url = "/categories/"

   [[menu.main]]
     identifier = "series"
     name = "Series"
     url = "/series/"
     
   [[menu.main]]
     identifier = "contact"
     name = "Contact"
     url = "/contact/"
     
  [[menu.social]]
    identifier = "mail"
    name = "Email"
    url = "mailto:ranabd36@gmail.com"
    
  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ranabd36"

  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/ranabd36"